// convex/lib/boilerplate/stripe/stripe/index.ts
// Barrel exports for stripe module

// Constants
export { STRIPE_CONSTANTS } from './constants';

// Types
export type {
  StripeCustomer,
  StripeSubscription,
  StripePayment,
  StripeWebhookEvent,
  SubscriptionStatus,
  PaymentStatus,
  CustomerStatus,
  WebhookStatus,
  BillingInterval,
  CollectionMethod,
  StripeAddress,
  InvoiceSettings,
  CreateCustomerInput,
  UpdateCustomerInput,
  CreateSubscriptionInput,
  UpdateSubscriptionInput,
  CreatePaymentInput,
  UpdatePaymentInput,
  RefundPaymentInput,
  WebhookEventInput,
  RevenueAnalytics,
  PlatformAnalytics,
  SubscriptionAnalytics,
  QueryOptions,
  SearchOptions,
  WebhookProcessingResult,
  StripeApiError,
  ValidationResult,
} from './types';

// Utilities
export {
  validateEmail,
  validateStripeCustomerId,
  validateStripeSubscriptionId,
  validateStripePaymentIntentId,
  validateCurrency,
  validatePaymentAmount,
  formatCurrency,
  validateCustomerInput,
  validateAddress,
  validateSubscriptionInput,
  validatePaymentInput,
  generateStripePublicId,
  generateCustomerPublicId,
  generateSubscriptionPublicId,
  generatePaymentPublicId,
  generateWebhookPublicId,
  calculateSubscriptionEndDate,
  isSubscriptionActive,
  isPaymentSuccessful,
  canRefundPayment,
  getRefundableAmount,
  parseWebhookEventType,
  shouldProcessWebhook,
  generateIdempotencyKey,
  sanitizeString,
  trimObjectFields,
  calculateMRR,
  calculateARR,
} from './utils';

// Permissions
export {
  isAuthenticated,
  isAdmin,
  canViewCustomer,
  canCreateCustomer,
  canUpdateCustomer,
  canDeleteCustomer,
  canViewSubscription,
  canCreateSubscription,
  canUpdateSubscription,
  canCancelSubscription,
  canViewPayment,
  canCreatePayment,
  canRefundPayment,
  canViewWebhookEvents,
  canProcessWebhookEvents,
  canViewAnalytics,
  canViewOwnAnalytics,
  assertAuthenticated,
  assertIsAdmin,
  assertCanViewCustomer,
  assertCanUpdateCustomer,
  assertCanViewSubscription,
  assertCanCancelSubscription,
  assertCanRefundPayment,
  filterCustomersByAccess,
  filterSubscriptionsByAccess,
  filterPaymentsByAccess,
} from './permissions';

// Queries
export {
  getCustomer,
  getCustomerByUserId,
  getCustomerByStripeId,
  listCustomers,
  getSubscription,
  getActiveSubscription,
  getSubscriptionsByUserId,
  getSubscriptionByStripeId,
  listSubscriptions,
  getPayment,
  getPaymentsByUserId,
  getPaymentByIntentId,
  listPayments,
  getSuccessfulPaymentsByUserId,
  getUserRevenueAnalytics,
  getPlatformRevenueAnalytics,
  getSubscriptionAnalytics,
  getWebhookEvent,
  listWebhookEvents,
} from './queries';

// Mutations
export {
  upsertCustomer,
  deleteCustomer,
  upsertSubscription,
  updateSubscriptionStatus,
  cancelSubscription,
  deleteSubscription,
  upsertPayment,
  updatePaymentStatus,
  markPaymentRefunded,
  processWebhookEvent,
  updateWebhookEventStatus,
} from './mutations';
