/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as config_entityTypes from "../config/entityTypes.js";
import type * as config_features_index from "../config/features/index.js";
import type * as config_index from "../config/index.js";
import type * as config_system_entities_index from "../config/system/entities/index.js";
import type * as config_types from "../config/types.js";
import type * as config_yourobc from "../config/yourobc.js";
import type * as lib_config_config from "../lib/config/config.js";
import type * as lib_system_analytics_constants from "../lib/system/analytics/constants.js";
import type * as lib_system_analytics_index from "../lib/system/analytics/index.js";
import type * as lib_system_analytics_mutations from "../lib/system/analytics/mutations.js";
import type * as lib_system_analytics_permissions from "../lib/system/analytics/permissions.js";
import type * as lib_system_analytics_queries from "../lib/system/analytics/queries.js";
import type * as lib_system_analytics_types from "../lib/system/analytics/types.js";
import type * as lib_system_analytics_utils from "../lib/system/analytics/utils.js";
import type * as lib_system_app_configs_constants from "../lib/system/app_configs/constants.js";
import type * as lib_system_app_configs_index from "../lib/system/app_configs/index.js";
import type * as lib_system_app_configs_mutations from "../lib/system/app_configs/mutations.js";
import type * as lib_system_app_configs_permissions from "../lib/system/app_configs/permissions.js";
import type * as lib_system_app_configs_queries from "../lib/system/app_configs/queries.js";
import type * as lib_system_app_configs_types from "../lib/system/app_configs/types.js";
import type * as lib_system_app_configs_utils from "../lib/system/app_configs/utils.js";
import type * as lib_system_app_settings_constants from "../lib/system/app_settings/constants.js";
import type * as lib_system_app_settings_index from "../lib/system/app_settings/index.js";
import type * as lib_system_app_settings_mutations from "../lib/system/app_settings/mutations.js";
import type * as lib_system_app_settings_permissions from "../lib/system/app_settings/permissions.js";
import type * as lib_system_app_settings_queries from "../lib/system/app_settings/queries.js";
import type * as lib_system_app_settings_types from "../lib/system/app_settings/types.js";
import type * as lib_system_app_settings_utils from "../lib/system/app_settings/utils.js";
import type * as lib_system_app_theme_settings_constants from "../lib/system/app_theme_settings/constants.js";
import type * as lib_system_app_theme_settings_index from "../lib/system/app_theme_settings/index.js";
import type * as lib_system_app_theme_settings_mutations from "../lib/system/app_theme_settings/mutations.js";
import type * as lib_system_app_theme_settings_permissions from "../lib/system/app_theme_settings/permissions.js";
import type * as lib_system_app_theme_settings_queries from "../lib/system/app_theme_settings/queries.js";
import type * as lib_system_app_theme_settings_types from "../lib/system/app_theme_settings/types.js";
import type * as lib_system_app_theme_settings_utils from "../lib/system/app_theme_settings/utils.js";
import type * as lib_system_audit_logs_admin_queries from "../lib/system/audit_logs/admin_queries.js";
import type * as lib_system_audit_logs_constants from "../lib/system/audit_logs/constants.js";
import type * as lib_system_audit_logs_entityTypes from "../lib/system/audit_logs/entityTypes.js";
import type * as lib_system_audit_logs_helpers from "../lib/system/audit_logs/helpers.js";
import type * as lib_system_audit_logs_index from "../lib/system/audit_logs/index.js";
import type * as lib_system_audit_logs_mutations from "../lib/system/audit_logs/mutations.js";
import type * as lib_system_audit_logs_permissions from "../lib/system/audit_logs/permissions.js";
import type * as lib_system_audit_logs_queries from "../lib/system/audit_logs/queries.js";
import type * as lib_system_audit_logs_types from "../lib/system/audit_logs/types.js";
import type * as lib_system_dashboards_constants from "../lib/system/dashboards/constants.js";
import type * as lib_system_dashboards_index from "../lib/system/dashboards/index.js";
import type * as lib_system_dashboards_mutations from "../lib/system/dashboards/mutations.js";
import type * as lib_system_dashboards_permissions from "../lib/system/dashboards/permissions.js";
import type * as lib_system_dashboards_queries from "../lib/system/dashboards/queries.js";
import type * as lib_system_dashboards_types from "../lib/system/dashboards/types.js";
import type * as lib_system_dashboards_utils from "../lib/system/dashboards/utils.js";
import type * as lib_system_email_configs_constants from "../lib/system/email/configs/constants.js";
import type * as lib_system_email_configs_index from "../lib/system/email/configs/index.js";
import type * as lib_system_email_configs_mutations from "../lib/system/email/configs/mutations.js";
import type * as lib_system_email_configs_permissions from "../lib/system/email/configs/permissions.js";
import type * as lib_system_email_configs_queries from "../lib/system/email/configs/queries.js";
import type * as lib_system_email_configs_types from "../lib/system/email/configs/types.js";
import type * as lib_system_email_configs_utils from "../lib/system/email/configs/utils.js";
import type * as lib_system_email_constants from "../lib/system/email/constants.js";
import type * as lib_system_email_email_templates_constants from "../lib/system/email/email_templates/constants.js";
import type * as lib_system_email_email_templates_index from "../lib/system/email/email_templates/index.js";
import type * as lib_system_email_email_templates_mutations from "../lib/system/email/email_templates/mutations.js";
import type * as lib_system_email_email_templates_permissions from "../lib/system/email/email_templates/permissions.js";
import type * as lib_system_email_email_templates_queries from "../lib/system/email/email_templates/queries.js";
import type * as lib_system_email_email_templates_types from "../lib/system/email/email_templates/types.js";
import type * as lib_system_email_email_templates_utils from "../lib/system/email/email_templates/utils.js";
import type * as lib_system_email_index from "../lib/system/email/index.js";
import type * as lib_system_email_mutations from "../lib/system/email/mutations.js";
import type * as lib_system_email_queries from "../lib/system/email/queries.js";
import type * as lib_system_email_types from "../lib/system/email/types.js";
import type * as lib_system_email_utils from "../lib/system/email/utils.js";
import type * as lib_system_notifications_constants from "../lib/system/notifications/constants.js";
import type * as lib_system_notifications_index from "../lib/system/notifications/index.js";
import type * as lib_system_notifications_mutations from "../lib/system/notifications/mutations.js";
import type * as lib_system_notifications_permissions from "../lib/system/notifications/permissions.js";
import type * as lib_system_notifications_queries from "../lib/system/notifications/queries.js";
import type * as lib_system_notifications_types from "../lib/system/notifications/types.js";
import type * as lib_system_notifications_utils from "../lib/system/notifications/utils.js";
import type * as lib_system_permission_requests_constants from "../lib/system/permission_requests/constants.js";
import type * as lib_system_permission_requests_index from "../lib/system/permission_requests/index.js";
import type * as lib_system_permission_requests_mutations from "../lib/system/permission_requests/mutations.js";
import type * as lib_system_permission_requests_permissions from "../lib/system/permission_requests/permissions.js";
import type * as lib_system_permission_requests_queries from "../lib/system/permission_requests/queries.js";
import type * as lib_system_permission_requests_types from "../lib/system/permission_requests/types.js";
import type * as lib_system_permission_requests_utils from "../lib/system/permission_requests/utils.js";
import type * as lib_system_supporting_comments from "../lib/system/supporting/comments.js";
import type * as lib_system_supporting_counters from "../lib/system/supporting/counters.js";
import type * as lib_system_supporting_documents from "../lib/system/supporting/documents.js";
import type * as lib_system_supporting_exchangeRates from "../lib/system/supporting/exchangeRates.js";
import type * as lib_system_supporting_followupReminders from "../lib/system/supporting/followupReminders.js";
import type * as lib_system_supporting_index from "../lib/system/supporting/index.js";
import type * as lib_system_supporting_inquirySources from "../lib/system/supporting/inquirySources.js";
import type * as lib_system_supporting_notifications from "../lib/system/supporting/notifications.js";
import type * as lib_system_supporting_schemas from "../lib/system/supporting/schemas.js";
import type * as lib_system_supporting_types from "../lib/system/supporting/types.js";
import type * as lib_system_supporting_validators from "../lib/system/supporting/validators.js";
import type * as lib_system_supporting_wikiEntries from "../lib/system/supporting/wikiEntries.js";
import type * as lib_system_system_metrics_constants from "../lib/system/system_metrics/constants.js";
import type * as lib_system_system_metrics_index from "../lib/system/system_metrics/index.js";
import type * as lib_system_system_metrics_mutations from "../lib/system/system_metrics/mutations.js";
import type * as lib_system_system_metrics_permissions from "../lib/system/system_metrics/permissions.js";
import type * as lib_system_system_metrics_queries from "../lib/system/system_metrics/queries.js";
import type * as lib_system_system_metrics_types from "../lib/system/system_metrics/types.js";
import type * as lib_system_system_metrics_utils from "../lib/system/system_metrics/utils.js";
import type * as lib_system_user_profiles_constants from "../lib/system/user_profiles/constants.js";
import type * as lib_system_user_profiles_index from "../lib/system/user_profiles/index.js";
import type * as lib_system_user_profiles_mutations from "../lib/system/user_profiles/mutations.js";
import type * as lib_system_user_profiles_permissions from "../lib/system/user_profiles/permissions.js";
import type * as lib_system_user_profiles_queries from "../lib/system/user_profiles/queries.js";
import type * as lib_system_user_profiles_types from "../lib/system/user_profiles/types.js";
import type * as lib_system_user_profiles_utils from "../lib/system/user_profiles/utils.js";
import type * as lib_system_user_settings_user_model_preferences_constants from "../lib/system/user_settings/user_model_preferences/constants.js";
import type * as lib_system_user_settings_user_model_preferences_index from "../lib/system/user_settings/user_model_preferences/index.js";
import type * as lib_system_user_settings_user_model_preferences_mutations from "../lib/system/user_settings/user_model_preferences/mutations.js";
import type * as lib_system_user_settings_user_model_preferences_permissions from "../lib/system/user_settings/user_model_preferences/permissions.js";
import type * as lib_system_user_settings_user_model_preferences_queries from "../lib/system/user_settings/user_model_preferences/queries.js";
import type * as lib_system_user_settings_user_model_preferences_types from "../lib/system/user_settings/user_model_preferences/types.js";
import type * as lib_system_user_settings_user_model_preferences_utils from "../lib/system/user_settings/user_model_preferences/utils.js";
import type * as lib_system_user_settings_user_settings_constants from "../lib/system/user_settings/user_settings/constants.js";
import type * as lib_system_user_settings_user_settings_index from "../lib/system/user_settings/user_settings/index.js";
import type * as lib_system_user_settings_user_settings_mutations from "../lib/system/user_settings/user_settings/mutations.js";
import type * as lib_system_user_settings_user_settings_permissions from "../lib/system/user_settings/user_settings/permissions.js";
import type * as lib_system_user_settings_user_settings_queries from "../lib/system/user_settings/user_settings/queries.js";
import type * as lib_system_user_settings_user_settings_types from "../lib/system/user_settings/user_settings/types.js";
import type * as lib_system_user_settings_user_settings_utils from "../lib/system/user_settings/user_settings/utils.js";
import type * as lib_yourobc_accounting_constants from "../lib/yourobc/accounting/constants.js";
import type * as lib_yourobc_accounting_index from "../lib/yourobc/accounting/index.js";
import type * as lib_yourobc_accounting_mutations from "../lib/yourobc/accounting/mutations.js";
import type * as lib_yourobc_accounting_permissions from "../lib/yourobc/accounting/permissions.js";
import type * as lib_yourobc_accounting_queries from "../lib/yourobc/accounting/queries.js";
import type * as lib_yourobc_accounting_types from "../lib/yourobc/accounting/types.js";
import type * as lib_yourobc_accounting_utils from "../lib/yourobc/accounting/utils.js";
import type * as lib_yourobc_couriers_constants from "../lib/yourobc/couriers/constants.js";
import type * as lib_yourobc_couriers_index from "../lib/yourobc/couriers/index.js";
import type * as lib_yourobc_couriers_mutations from "../lib/yourobc/couriers/mutations.js";
import type * as lib_yourobc_couriers_permissions from "../lib/yourobc/couriers/permissions.js";
import type * as lib_yourobc_couriers_queries from "../lib/yourobc/couriers/queries.js";
import type * as lib_yourobc_couriers_types from "../lib/yourobc/couriers/types.js";
import type * as lib_yourobc_couriers_utils from "../lib/yourobc/couriers/utils.js";
import type * as lib_yourobc_customerMargins_constants from "../lib/yourobc/customerMargins/constants.js";
import type * as lib_yourobc_customerMargins_index from "../lib/yourobc/customerMargins/index.js";
import type * as lib_yourobc_customerMargins_mutations from "../lib/yourobc/customerMargins/mutations.js";
import type * as lib_yourobc_customerMargins_permissions from "../lib/yourobc/customerMargins/permissions.js";
import type * as lib_yourobc_customerMargins_queries from "../lib/yourobc/customerMargins/queries.js";
import type * as lib_yourobc_customerMargins_types from "../lib/yourobc/customerMargins/types.js";
import type * as lib_yourobc_customerMargins_utils from "../lib/yourobc/customerMargins/utils.js";
import type * as lib_yourobc_customers_bulkHelpers from "../lib/yourobc/customers/bulkHelpers.js";
import type * as lib_yourobc_customers_constants from "../lib/yourobc/customers/constants.js";
import type * as lib_yourobc_customers_index from "../lib/yourobc/customers/index.js";
import type * as lib_yourobc_customers_mutations from "../lib/yourobc/customers/mutations.js";
import type * as lib_yourobc_customers_permissions from "../lib/yourobc/customers/permissions.js";
import type * as lib_yourobc_customers_queries from "../lib/yourobc/customers/queries.js";
import type * as lib_yourobc_customers_types from "../lib/yourobc/customers/types.js";
import type * as lib_yourobc_customers_utils from "../lib/yourobc/customers/utils.js";
import type * as lib_yourobc_dashboard_constants from "../lib/yourobc/dashboard/constants.js";
import type * as lib_yourobc_dashboard_index from "../lib/yourobc/dashboard/index.js";
import type * as lib_yourobc_dashboard_mutations from "../lib/yourobc/dashboard/mutations.js";
import type * as lib_yourobc_dashboard_permissions from "../lib/yourobc/dashboard/permissions.js";
import type * as lib_yourobc_dashboard_queries from "../lib/yourobc/dashboard/queries.js";
import type * as lib_yourobc_dashboard_types from "../lib/yourobc/dashboard/types.js";
import type * as lib_yourobc_dashboard_utils from "../lib/yourobc/dashboard/utils.js";
import type * as lib_yourobc_employeeCommissions_constants from "../lib/yourobc/employeeCommissions/constants.js";
import type * as lib_yourobc_employeeCommissions_index from "../lib/yourobc/employeeCommissions/index.js";
import type * as lib_yourobc_employeeCommissions_mutations from "../lib/yourobc/employeeCommissions/mutations.js";
import type * as lib_yourobc_employeeCommissions_permissions from "../lib/yourobc/employeeCommissions/permissions.js";
import type * as lib_yourobc_employeeCommissions_queries from "../lib/yourobc/employeeCommissions/queries.js";
import type * as lib_yourobc_employeeCommissions_types from "../lib/yourobc/employeeCommissions/types.js";
import type * as lib_yourobc_employeeCommissions_utils from "../lib/yourobc/employeeCommissions/utils.js";
import type * as lib_yourobc_employeeKPIs_constants from "../lib/yourobc/employeeKPIs/constants.js";
import type * as lib_yourobc_employeeKPIs_index from "../lib/yourobc/employeeKPIs/index.js";
import type * as lib_yourobc_employeeKPIs_mutations from "../lib/yourobc/employeeKPIs/mutations.js";
import type * as lib_yourobc_employeeKPIs_permissions from "../lib/yourobc/employeeKPIs/permissions.js";
import type * as lib_yourobc_employeeKPIs_queries from "../lib/yourobc/employeeKPIs/queries.js";
import type * as lib_yourobc_employeeKPIs_types from "../lib/yourobc/employeeKPIs/types.js";
import type * as lib_yourobc_employeeKPIs_utils from "../lib/yourobc/employeeKPIs/utils.js";
import type * as lib_yourobc_employeeSessions_constants from "../lib/yourobc/employeeSessions/constants.js";
import type * as lib_yourobc_employeeSessions_index from "../lib/yourobc/employeeSessions/index.js";
import type * as lib_yourobc_employeeSessions_mutations from "../lib/yourobc/employeeSessions/mutations.js";
import type * as lib_yourobc_employeeSessions_permissions from "../lib/yourobc/employeeSessions/permissions.js";
import type * as lib_yourobc_employeeSessions_queries from "../lib/yourobc/employeeSessions/queries.js";
import type * as lib_yourobc_employeeSessions_types from "../lib/yourobc/employeeSessions/types.js";
import type * as lib_yourobc_employeeSessions_utils from "../lib/yourobc/employeeSessions/utils.js";
import type * as lib_yourobc_employees_constants from "../lib/yourobc/employees/constants.js";
import type * as lib_yourobc_employees_index from "../lib/yourobc/employees/index.js";
import type * as lib_yourobc_employees_mutations from "../lib/yourobc/employees/mutations.js";
import type * as lib_yourobc_employees_permissions from "../lib/yourobc/employees/permissions.js";
import type * as lib_yourobc_employees_queries from "../lib/yourobc/employees/queries.js";
import type * as lib_yourobc_employees_types from "../lib/yourobc/employees/types.js";
import type * as lib_yourobc_employees_utils from "../lib/yourobc/employees/utils.js";
import type * as lib_yourobc_invoices_constants from "../lib/yourobc/invoices/constants.js";
import type * as lib_yourobc_invoices_index from "../lib/yourobc/invoices/index.js";
import type * as lib_yourobc_invoices_mutations from "../lib/yourobc/invoices/mutations.js";
import type * as lib_yourobc_invoices_permissions from "../lib/yourobc/invoices/permissions.js";
import type * as lib_yourobc_invoices_queries from "../lib/yourobc/invoices/queries.js";
import type * as lib_yourobc_invoices_types from "../lib/yourobc/invoices/types.js";
import type * as lib_yourobc_invoices_utils from "../lib/yourobc/invoices/utils.js";
import type * as lib_yourobc_partners_constants from "../lib/yourobc/partners/constants.js";
import type * as lib_yourobc_partners_index from "../lib/yourobc/partners/index.js";
import type * as lib_yourobc_partners_mutations from "../lib/yourobc/partners/mutations.js";
import type * as lib_yourobc_partners_permissions from "../lib/yourobc/partners/permissions.js";
import type * as lib_yourobc_partners_queries from "../lib/yourobc/partners/queries.js";
import type * as lib_yourobc_partners_types from "../lib/yourobc/partners/types.js";
import type * as lib_yourobc_partners_utils from "../lib/yourobc/partners/utils.js";
import type * as lib_yourobc_quotes_constants from "../lib/yourobc/quotes/constants.js";
import type * as lib_yourobc_quotes_index from "../lib/yourobc/quotes/index.js";
import type * as lib_yourobc_quotes_mutations from "../lib/yourobc/quotes/mutations.js";
import type * as lib_yourobc_quotes_permissions from "../lib/yourobc/quotes/permissions.js";
import type * as lib_yourobc_quotes_queries from "../lib/yourobc/quotes/queries.js";
import type * as lib_yourobc_quotes_types from "../lib/yourobc/quotes/types.js";
import type * as lib_yourobc_quotes_utils from "../lib/yourobc/quotes/utils.js";
import type * as lib_yourobc_shared_calculations from "../lib/yourobc/shared/calculations.js";
import type * as lib_yourobc_shared_constants from "../lib/yourobc/shared/constants.js";
import type * as lib_yourobc_shared_formatting from "../lib/yourobc/shared/formatting.js";
import type * as lib_yourobc_shared_generators from "../lib/yourobc/shared/generators.js";
import type * as lib_yourobc_shared_index from "../lib/yourobc/shared/index.js";
import type * as lib_yourobc_shared_types from "../lib/yourobc/shared/types.js";
import type * as lib_yourobc_shared_utils from "../lib/yourobc/shared/utils.js";
import type * as lib_yourobc_shared_validation from "../lib/yourobc/shared/validation.js";
import type * as lib_yourobc_shipments_constants from "../lib/yourobc/shipments/constants.js";
import type * as lib_yourobc_shipments_index from "../lib/yourobc/shipments/index.js";
import type * as lib_yourobc_shipments_mutations from "../lib/yourobc/shipments/mutations.js";
import type * as lib_yourobc_shipments_permissions from "../lib/yourobc/shipments/permissions.js";
import type * as lib_yourobc_shipments_queries from "../lib/yourobc/shipments/queries.js";
import type * as lib_yourobc_shipments_types from "../lib/yourobc/shipments/types.js";
import type * as lib_yourobc_shipments_utils from "../lib/yourobc/shipments/utils.js";
import type * as lib_yourobc_statistics_constants from "../lib/yourobc/statistics/constants.js";
import type * as lib_yourobc_statistics_index from "../lib/yourobc/statistics/index.js";
import type * as lib_yourobc_statistics_mutations from "../lib/yourobc/statistics/mutations.js";
import type * as lib_yourobc_statistics_permissions from "../lib/yourobc/statistics/permissions.js";
import type * as lib_yourobc_statistics_queries from "../lib/yourobc/statistics/queries.js";
import type * as lib_yourobc_statistics_types from "../lib/yourobc/statistics/types.js";
import type * as lib_yourobc_statistics_utils from "../lib/yourobc/statistics/utils.js";
import type * as lib_yourobc_supporting_constants from "../lib/yourobc/supporting/constants.js";
import type * as lib_yourobc_supporting_index from "../lib/yourobc/supporting/index.js";
import type * as lib_yourobc_supporting_mutations from "../lib/yourobc/supporting/mutations.js";
import type * as lib_yourobc_supporting_permissions from "../lib/yourobc/supporting/permissions.js";
import type * as lib_yourobc_supporting_queries from "../lib/yourobc/supporting/queries.js";
import type * as lib_yourobc_supporting_types from "../lib/yourobc/supporting/types.js";
import type * as lib_yourobc_supporting_utils from "../lib/yourobc/supporting/utils.js";
import type * as lib_yourobc_tasks_constants from "../lib/yourobc/tasks/constants.js";
import type * as lib_yourobc_tasks_index from "../lib/yourobc/tasks/index.js";
import type * as lib_yourobc_tasks_mutations from "../lib/yourobc/tasks/mutations.js";
import type * as lib_yourobc_tasks_permissions from "../lib/yourobc/tasks/permissions.js";
import type * as lib_yourobc_tasks_queries from "../lib/yourobc/tasks/queries.js";
import type * as lib_yourobc_tasks_types from "../lib/yourobc/tasks/types.js";
import type * as lib_yourobc_tasks_utils from "../lib/yourobc/tasks/utils.js";
import type * as lib_yourobc_trackingMessages_constants from "../lib/yourobc/trackingMessages/constants.js";
import type * as lib_yourobc_trackingMessages_index from "../lib/yourobc/trackingMessages/index.js";
import type * as lib_yourobc_trackingMessages_mutations from "../lib/yourobc/trackingMessages/mutations.js";
import type * as lib_yourobc_trackingMessages_permissions from "../lib/yourobc/trackingMessages/permissions.js";
import type * as lib_yourobc_trackingMessages_queries from "../lib/yourobc/trackingMessages/queries.js";
import type * as lib_yourobc_trackingMessages_types from "../lib/yourobc/trackingMessages/types.js";
import type * as lib_yourobc_trackingMessages_utils from "../lib/yourobc/trackingMessages/utils.js";
import type * as schema_base from "../schema/base.js";
import type * as schema_system_analytics_analytics from "../schema/system/analytics/analytics.js";
import type * as schema_system_analytics_schemas from "../schema/system/analytics/schemas.js";
import type * as schema_system_analytics_types from "../schema/system/analytics/types.js";
import type * as schema_system_analytics_validators from "../schema/system/analytics/validators.js";
import type * as schema_system_appConfigs_appConfigs from "../schema/system/appConfigs/appConfigs.js";
import type * as schema_system_appConfigs_schemas from "../schema/system/appConfigs/schemas.js";
import type * as schema_system_appConfigs_types from "../schema/system/appConfigs/types.js";
import type * as schema_system_appConfigs_validators from "../schema/system/appConfigs/validators.js";
import type * as schema_system_appSettings_appSettings from "../schema/system/appSettings/appSettings.js";
import type * as schema_system_appSettings_schemas from "../schema/system/appSettings/schemas.js";
import type * as schema_system_appSettings_validators from "../schema/system/appSettings/validators.js";
import type * as schema_system_appThemeSettings_appThemeSettings from "../schema/system/appThemeSettings/appThemeSettings.js";
import type * as schema_system_appThemeSettings_schemas from "../schema/system/appThemeSettings/schemas.js";
import type * as schema_system_appThemeSettings_validators from "../schema/system/appThemeSettings/validators.js";
import type * as schema_system_auditLogs_auditLogs from "../schema/system/auditLogs/auditLogs.js";
import type * as schema_system_auditLogs_schemas from "../schema/system/auditLogs/schemas.js";
import type * as schema_system_auditLogs_types from "../schema/system/auditLogs/types.js";
import type * as schema_system_auditLogs_validators from "../schema/system/auditLogs/validators.js";
import type * as schema_system_dashboards_dashboards from "../schema/system/dashboards/dashboards.js";
import type * as schema_system_dashboards_schemas from "../schema/system/dashboards/schemas.js";
import type * as schema_system_dashboards_types from "../schema/system/dashboards/types.js";
import type * as schema_system_dashboards_validators from "../schema/system/dashboards/validators.js";
import type * as schema_system_email_configs from "../schema/system/email/configs.js";
import type * as schema_system_email_logs from "../schema/system/email/logs.js";
import type * as schema_system_email_schemas from "../schema/system/email/schemas.js";
import type * as schema_system_email_templates from "../schema/system/email/templates.js";
import type * as schema_system_email_types from "../schema/system/email/types.js";
import type * as schema_system_email_validators from "../schema/system/email/validators.js";
import type * as schema_system_index from "../schema/system/index.js";
import type * as schema_system_notifications_notifications from "../schema/system/notifications/notifications.js";
import type * as schema_system_notifications_schemas from "../schema/system/notifications/schemas.js";
import type * as schema_system_notifications_types from "../schema/system/notifications/types.js";
import type * as schema_system_notifications_validators from "../schema/system/notifications/validators.js";
import type * as schema_system_permissionRequests_permissionRequests from "../schema/system/permissionRequests/permissionRequests.js";
import type * as schema_system_permissionRequests_schemas from "../schema/system/permissionRequests/schemas.js";
import type * as schema_system_permissionRequests_types from "../schema/system/permissionRequests/types.js";
import type * as schema_system_permissionRequests_validators from "../schema/system/permissionRequests/validators.js";
import type * as schema_system_schemas from "../schema/system/schemas.js";
import type * as schema_system_supporting_comments from "../schema/system/supporting/comments.js";
import type * as schema_system_supporting_counters from "../schema/system/supporting/counters.js";
import type * as schema_system_supporting_documents from "../schema/system/supporting/documents.js";
import type * as schema_system_supporting_exchangeRates from "../schema/system/supporting/exchangeRates.js";
import type * as schema_system_supporting_followupReminders from "../schema/system/supporting/followupReminders.js";
import type * as schema_system_supporting_index from "../schema/system/supporting/index.js";
import type * as schema_system_supporting_inquirySources from "../schema/system/supporting/inquirySources.js";
import type * as schema_system_supporting_notifications from "../schema/system/supporting/notifications.js";
import type * as schema_system_supporting_schemas from "../schema/system/supporting/schemas.js";
import type * as schema_system_supporting_types from "../schema/system/supporting/types.js";
import type * as schema_system_supporting_validators from "../schema/system/supporting/validators.js";
import type * as schema_system_supporting_wikiEntries from "../schema/system/supporting/wikiEntries.js";
import type * as schema_system_systemMetrics_schemas from "../schema/system/systemMetrics/schemas.js";
import type * as schema_system_systemMetrics_systemMetrics from "../schema/system/systemMetrics/systemMetrics.js";
import type * as schema_system_systemMetrics_validators from "../schema/system/systemMetrics/validators.js";
import type * as schema_system_types from "../schema/system/types.js";
import type * as schema_system_user_profiles_schemas from "../schema/system/user_profiles/schemas.js";
import type * as schema_system_user_profiles_types from "../schema/system/user_profiles/types.js";
import type * as schema_system_user_profiles_user_profiles from "../schema/system/user_profiles/user_profiles.js";
import type * as schema_system_user_profiles_validators from "../schema/system/user_profiles/validators.js";
import type * as schema_system_user_settings_user_model_preferences_schemas from "../schema/system/user_settings/user_model_preferences/schemas.js";
import type * as schema_system_user_settings_user_model_preferences_types from "../schema/system/user_settings/user_model_preferences/types.js";
import type * as schema_system_user_settings_user_model_preferences_user_model_preferences from "../schema/system/user_settings/user_model_preferences/user_model_preferences.js";
import type * as schema_system_user_settings_user_model_preferences_validators from "../schema/system/user_settings/user_model_preferences/validators.js";
import type * as schema_system_user_settings_user_settings_schemas from "../schema/system/user_settings/user_settings/schemas.js";
import type * as schema_system_user_settings_user_settings_types from "../schema/system/user_settings/user_settings/types.js";
import type * as schema_system_user_settings_user_settings_user_settings from "../schema/system/user_settings/user_settings/user_settings.js";
import type * as schema_system_user_settings_user_settings_validators from "../schema/system/user_settings/user_settings/validators.js";
import type * as schema_system_validators from "../schema/system/validators.js";
import type * as schema_yourobc_accounting_accounting from "../schema/yourobc/accounting/accounting.js";
import type * as schema_yourobc_accounting_accountingDashboardCache from "../schema/yourobc/accounting/accountingDashboardCache.js";
import type * as schema_yourobc_accounting_incomingInvoiceTracking from "../schema/yourobc/accounting/incomingInvoiceTracking.js";
import type * as schema_yourobc_accounting_index from "../schema/yourobc/accounting/index.js";
import type * as schema_yourobc_accounting_invoiceAutoGenLog from "../schema/yourobc/accounting/invoiceAutoGenLog.js";
import type * as schema_yourobc_accounting_invoiceNumbering from "../schema/yourobc/accounting/invoiceNumbering.js";
import type * as schema_yourobc_accounting_schemas from "../schema/yourobc/accounting/schemas.js";
import type * as schema_yourobc_accounting_statementOfAccounts from "../schema/yourobc/accounting/statementOfAccounts.js";
import type * as schema_yourobc_accounting_types from "../schema/yourobc/accounting/types.js";
import type * as schema_yourobc_accounting_validators from "../schema/yourobc/accounting/validators.js";
import type * as schema_yourobc_couriers_commissions from "../schema/yourobc/couriers/commissions.js";
import type * as schema_yourobc_couriers_couriers from "../schema/yourobc/couriers/couriers.js";
import type * as schema_yourobc_couriers_index from "../schema/yourobc/couriers/index.js";
import type * as schema_yourobc_couriers_schemas from "../schema/yourobc/couriers/schemas.js";
import type * as schema_yourobc_couriers_types from "../schema/yourobc/couriers/types.js";
import type * as schema_yourobc_couriers_validators from "../schema/yourobc/couriers/validators.js";
import type * as schema_yourobc_customerMargins_contactLog from "../schema/yourobc/customerMargins/contactLog.js";
import type * as schema_yourobc_customerMargins_customerAnalytics from "../schema/yourobc/customerMargins/customerAnalytics.js";
import type * as schema_yourobc_customerMargins_customerDunningConfig from "../schema/yourobc/customerMargins/customerDunningConfig.js";
import type * as schema_yourobc_customerMargins_customerMargins from "../schema/yourobc/customerMargins/customerMargins.js";
import type * as schema_yourobc_customerMargins_index from "../schema/yourobc/customerMargins/index.js";
import type * as schema_yourobc_customerMargins_schemas from "../schema/yourobc/customerMargins/schemas.js";
import type * as schema_yourobc_customerMargins_types from "../schema/yourobc/customerMargins/types.js";
import type * as schema_yourobc_customerMargins_validators from "../schema/yourobc/customerMargins/validators.js";
import type * as schema_yourobc_customers_customers from "../schema/yourobc/customers/customers.js";
import type * as schema_yourobc_customers_index from "../schema/yourobc/customers/index.js";
import type * as schema_yourobc_customers_schemas from "../schema/yourobc/customers/schemas.js";
import type * as schema_yourobc_customers_types from "../schema/yourobc/customers/types.js";
import type * as schema_yourobc_customers_validators from "../schema/yourobc/customers/validators.js";
import type * as schema_yourobc_dashboard_dashboardAlertAcknowledgments from "../schema/yourobc/dashboard/dashboardAlertAcknowledgments.js";
import type * as schema_yourobc_dashboard_index from "../schema/yourobc/dashboard/index.js";
import type * as schema_yourobc_dashboard_schemas from "../schema/yourobc/dashboard/schemas.js";
import type * as schema_yourobc_dashboard_types from "../schema/yourobc/dashboard/types.js";
import type * as schema_yourobc_dashboard_validators from "../schema/yourobc/dashboard/validators.js";
import type * as schema_yourobc_employeeCommissions_employeeCommissionRules from "../schema/yourobc/employeeCommissions/employeeCommissionRules.js";
import type * as schema_yourobc_employeeCommissions_employeeCommissions from "../schema/yourobc/employeeCommissions/employeeCommissions.js";
import type * as schema_yourobc_employeeCommissions_index from "../schema/yourobc/employeeCommissions/index.js";
import type * as schema_yourobc_employeeCommissions_schemas from "../schema/yourobc/employeeCommissions/schemas.js";
import type * as schema_yourobc_employeeCommissions_types from "../schema/yourobc/employeeCommissions/types.js";
import type * as schema_yourobc_employeeCommissions_validators from "../schema/yourobc/employeeCommissions/validators.js";
import type * as schema_yourobc_employeeKPIs_employeeKPIs from "../schema/yourobc/employeeKPIs/employeeKPIs.js";
import type * as schema_yourobc_employeeKPIs_employeeTargets from "../schema/yourobc/employeeKPIs/employeeTargets.js";
import type * as schema_yourobc_employeeKPIs_index from "../schema/yourobc/employeeKPIs/index.js";
import type * as schema_yourobc_employeeKPIs_schemas from "../schema/yourobc/employeeKPIs/schemas.js";
import type * as schema_yourobc_employeeKPIs_types from "../schema/yourobc/employeeKPIs/types.js";
import type * as schema_yourobc_employeeKPIs_validators from "../schema/yourobc/employeeKPIs/validators.js";
import type * as schema_yourobc_employeeSessions_employeeSessions from "../schema/yourobc/employeeSessions/employeeSessions.js";
import type * as schema_yourobc_employeeSessions_index from "../schema/yourobc/employeeSessions/index.js";
import type * as schema_yourobc_employeeSessions_schemas from "../schema/yourobc/employeeSessions/schemas.js";
import type * as schema_yourobc_employeeSessions_types from "../schema/yourobc/employeeSessions/types.js";
import type * as schema_yourobc_employeeSessions_validators from "../schema/yourobc/employeeSessions/validators.js";
import type * as schema_yourobc_employeeSessions_workHoursSummary from "../schema/yourobc/employeeSessions/workHoursSummary.js";
import type * as schema_yourobc_employees_employees from "../schema/yourobc/employees/employees.js";
import type * as schema_yourobc_employees_index from "../schema/yourobc/employees/index.js";
import type * as schema_yourobc_employees_schemas from "../schema/yourobc/employees/schemas.js";
import type * as schema_yourobc_employees_types from "../schema/yourobc/employees/types.js";
import type * as schema_yourobc_employees_vacationDays from "../schema/yourobc/employees/vacationDays.js";
import type * as schema_yourobc_employees_validators from "../schema/yourobc/employees/validators.js";
import type * as schema_yourobc_index from "../schema/yourobc/index.js";
import type * as schema_yourobc_invoices_index from "../schema/yourobc/invoices/index.js";
import type * as schema_yourobc_invoices_invoices from "../schema/yourobc/invoices/invoices.js";
import type * as schema_yourobc_invoices_schemas from "../schema/yourobc/invoices/schemas.js";
import type * as schema_yourobc_invoices_types from "../schema/yourobc/invoices/types.js";
import type * as schema_yourobc_invoices_validators from "../schema/yourobc/invoices/validators.js";
import type * as schema_yourobc_partners_index from "../schema/yourobc/partners/index.js";
import type * as schema_yourobc_partners_partners from "../schema/yourobc/partners/partners.js";
import type * as schema_yourobc_partners_schemas from "../schema/yourobc/partners/schemas.js";
import type * as schema_yourobc_partners_types from "../schema/yourobc/partners/types.js";
import type * as schema_yourobc_partners_validators from "../schema/yourobc/partners/validators.js";
import type * as schema_yourobc_quotes_index from "../schema/yourobc/quotes/index.js";
import type * as schema_yourobc_quotes_quotes from "../schema/yourobc/quotes/quotes.js";
import type * as schema_yourobc_quotes_schemas from "../schema/yourobc/quotes/schemas.js";
import type * as schema_yourobc_quotes_types from "../schema/yourobc/quotes/types.js";
import type * as schema_yourobc_quotes_validators from "../schema/yourobc/quotes/validators.js";
import type * as schema_yourobc_schemas from "../schema/yourobc/schemas.js";
import type * as schema_yourobc_shipments_index from "../schema/yourobc/shipments/index.js";
import type * as schema_yourobc_shipments_schemas from "../schema/yourobc/shipments/schemas.js";
import type * as schema_yourobc_shipments_shipmentStatusHistory from "../schema/yourobc/shipments/shipmentStatusHistory.js";
import type * as schema_yourobc_shipments_shipments from "../schema/yourobc/shipments/shipments.js";
import type * as schema_yourobc_shipments_types from "../schema/yourobc/shipments/types.js";
import type * as schema_yourobc_shipments_validators from "../schema/yourobc/shipments/validators.js";
import type * as schema_yourobc_statistics_employeeCosts from "../schema/yourobc/statistics/employeeCosts.js";
import type * as schema_yourobc_statistics_index from "../schema/yourobc/statistics/index.js";
import type * as schema_yourobc_statistics_kpiCache from "../schema/yourobc/statistics/kpiCache.js";
import type * as schema_yourobc_statistics_kpiTargets from "../schema/yourobc/statistics/kpiTargets.js";
import type * as schema_yourobc_statistics_miscExpenses from "../schema/yourobc/statistics/miscExpenses.js";
import type * as schema_yourobc_statistics_officeCosts from "../schema/yourobc/statistics/officeCosts.js";
import type * as schema_yourobc_statistics_schemas from "../schema/yourobc/statistics/schemas.js";
import type * as schema_yourobc_statistics_types from "../schema/yourobc/statistics/types.js";
import type * as schema_yourobc_statistics_validators from "../schema/yourobc/statistics/validators.js";
import type * as schema_yourobc_supporting_comments from "../schema/yourobc/supporting/comments.js";
import type * as schema_yourobc_supporting_counters from "../schema/yourobc/supporting/counters.js";
import type * as schema_yourobc_supporting_documents from "../schema/yourobc/supporting/documents.js";
import type * as schema_yourobc_supporting_exchangeRates from "../schema/yourobc/supporting/exchangeRates.js";
import type * as schema_yourobc_supporting_followupReminders from "../schema/yourobc/supporting/followupReminders.js";
import type * as schema_yourobc_supporting_index from "../schema/yourobc/supporting/index.js";
import type * as schema_yourobc_supporting_inquirySources from "../schema/yourobc/supporting/inquirySources.js";
import type * as schema_yourobc_supporting_notifications from "../schema/yourobc/supporting/notifications.js";
import type * as schema_yourobc_supporting_schemas from "../schema/yourobc/supporting/schemas.js";
import type * as schema_yourobc_supporting_types from "../schema/yourobc/supporting/types.js";
import type * as schema_yourobc_supporting_validators from "../schema/yourobc/supporting/validators.js";
import type * as schema_yourobc_supporting_wikiEntries from "../schema/yourobc/supporting/wikiEntries.js";
import type * as schema_yourobc_tasks_index from "../schema/yourobc/tasks/index.js";
import type * as schema_yourobc_tasks_schemas from "../schema/yourobc/tasks/schemas.js";
import type * as schema_yourobc_tasks_tasks from "../schema/yourobc/tasks/tasks.js";
import type * as schema_yourobc_tasks_types from "../schema/yourobc/tasks/types.js";
import type * as schema_yourobc_tasks_validators from "../schema/yourobc/tasks/validators.js";
import type * as schema_yourobc_trackingMessages_index from "../schema/yourobc/trackingMessages/index.js";
import type * as schema_yourobc_trackingMessages_schemas from "../schema/yourobc/trackingMessages/schemas.js";
import type * as schema_yourobc_trackingMessages_trackingMessages from "../schema/yourobc/trackingMessages/trackingMessages.js";
import type * as schema_yourobc_trackingMessages_types from "../schema/yourobc/trackingMessages/types.js";
import type * as schema_yourobc_trackingMessages_validators from "../schema/yourobc/trackingMessages/validators.js";
import type * as schema_yourobc_types from "../schema/yourobc/types.js";
import type * as schema_yourobc_validators from "../schema/yourobc/validators.js";
import type * as shared_config_publicId from "../shared/config/publicId.js";
import type * as shared_errors from "../shared/errors.js";
import type * as shared_security_encryption from "../shared/security/encryption.js";
import type * as shared_security_envHelper from "../shared/security/envHelper.js";
import type * as shared_security_keyCache from "../shared/security/keyCache.js";
import type * as shared_security_rate_limiter from "../shared/security/rate_limiter.js";
import type * as shared_utils_id_resolution from "../shared/utils/id_resolution.js";
import type * as shared_utils_publicId from "../shared/utils/publicId.js";
import type * as shared_validators from "../shared/validators.js";
import type * as test_authTest from "../test/authTest.js";
import type * as types from "../types.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "config/entityTypes": typeof config_entityTypes;
  "config/features/index": typeof config_features_index;
  "config/index": typeof config_index;
  "config/system/entities/index": typeof config_system_entities_index;
  "config/types": typeof config_types;
  "config/yourobc": typeof config_yourobc;
  "lib/config/config": typeof lib_config_config;
  "lib/system/analytics/constants": typeof lib_system_analytics_constants;
  "lib/system/analytics/index": typeof lib_system_analytics_index;
  "lib/system/analytics/mutations": typeof lib_system_analytics_mutations;
  "lib/system/analytics/permissions": typeof lib_system_analytics_permissions;
  "lib/system/analytics/queries": typeof lib_system_analytics_queries;
  "lib/system/analytics/types": typeof lib_system_analytics_types;
  "lib/system/analytics/utils": typeof lib_system_analytics_utils;
  "lib/system/app_configs/constants": typeof lib_system_app_configs_constants;
  "lib/system/app_configs/index": typeof lib_system_app_configs_index;
  "lib/system/app_configs/mutations": typeof lib_system_app_configs_mutations;
  "lib/system/app_configs/permissions": typeof lib_system_app_configs_permissions;
  "lib/system/app_configs/queries": typeof lib_system_app_configs_queries;
  "lib/system/app_configs/types": typeof lib_system_app_configs_types;
  "lib/system/app_configs/utils": typeof lib_system_app_configs_utils;
  "lib/system/app_settings/constants": typeof lib_system_app_settings_constants;
  "lib/system/app_settings/index": typeof lib_system_app_settings_index;
  "lib/system/app_settings/mutations": typeof lib_system_app_settings_mutations;
  "lib/system/app_settings/permissions": typeof lib_system_app_settings_permissions;
  "lib/system/app_settings/queries": typeof lib_system_app_settings_queries;
  "lib/system/app_settings/types": typeof lib_system_app_settings_types;
  "lib/system/app_settings/utils": typeof lib_system_app_settings_utils;
  "lib/system/app_theme_settings/constants": typeof lib_system_app_theme_settings_constants;
  "lib/system/app_theme_settings/index": typeof lib_system_app_theme_settings_index;
  "lib/system/app_theme_settings/mutations": typeof lib_system_app_theme_settings_mutations;
  "lib/system/app_theme_settings/permissions": typeof lib_system_app_theme_settings_permissions;
  "lib/system/app_theme_settings/queries": typeof lib_system_app_theme_settings_queries;
  "lib/system/app_theme_settings/types": typeof lib_system_app_theme_settings_types;
  "lib/system/app_theme_settings/utils": typeof lib_system_app_theme_settings_utils;
  "lib/system/audit_logs/admin_queries": typeof lib_system_audit_logs_admin_queries;
  "lib/system/audit_logs/constants": typeof lib_system_audit_logs_constants;
  "lib/system/audit_logs/entityTypes": typeof lib_system_audit_logs_entityTypes;
  "lib/system/audit_logs/helpers": typeof lib_system_audit_logs_helpers;
  "lib/system/audit_logs/index": typeof lib_system_audit_logs_index;
  "lib/system/audit_logs/mutations": typeof lib_system_audit_logs_mutations;
  "lib/system/audit_logs/permissions": typeof lib_system_audit_logs_permissions;
  "lib/system/audit_logs/queries": typeof lib_system_audit_logs_queries;
  "lib/system/audit_logs/types": typeof lib_system_audit_logs_types;
  "lib/system/dashboards/constants": typeof lib_system_dashboards_constants;
  "lib/system/dashboards/index": typeof lib_system_dashboards_index;
  "lib/system/dashboards/mutations": typeof lib_system_dashboards_mutations;
  "lib/system/dashboards/permissions": typeof lib_system_dashboards_permissions;
  "lib/system/dashboards/queries": typeof lib_system_dashboards_queries;
  "lib/system/dashboards/types": typeof lib_system_dashboards_types;
  "lib/system/dashboards/utils": typeof lib_system_dashboards_utils;
  "lib/system/email/configs/constants": typeof lib_system_email_configs_constants;
  "lib/system/email/configs/index": typeof lib_system_email_configs_index;
  "lib/system/email/configs/mutations": typeof lib_system_email_configs_mutations;
  "lib/system/email/configs/permissions": typeof lib_system_email_configs_permissions;
  "lib/system/email/configs/queries": typeof lib_system_email_configs_queries;
  "lib/system/email/configs/types": typeof lib_system_email_configs_types;
  "lib/system/email/configs/utils": typeof lib_system_email_configs_utils;
  "lib/system/email/constants": typeof lib_system_email_constants;
  "lib/system/email/email_templates/constants": typeof lib_system_email_email_templates_constants;
  "lib/system/email/email_templates/index": typeof lib_system_email_email_templates_index;
  "lib/system/email/email_templates/mutations": typeof lib_system_email_email_templates_mutations;
  "lib/system/email/email_templates/permissions": typeof lib_system_email_email_templates_permissions;
  "lib/system/email/email_templates/queries": typeof lib_system_email_email_templates_queries;
  "lib/system/email/email_templates/types": typeof lib_system_email_email_templates_types;
  "lib/system/email/email_templates/utils": typeof lib_system_email_email_templates_utils;
  "lib/system/email/index": typeof lib_system_email_index;
  "lib/system/email/mutations": typeof lib_system_email_mutations;
  "lib/system/email/queries": typeof lib_system_email_queries;
  "lib/system/email/types": typeof lib_system_email_types;
  "lib/system/email/utils": typeof lib_system_email_utils;
  "lib/system/notifications/constants": typeof lib_system_notifications_constants;
  "lib/system/notifications/index": typeof lib_system_notifications_index;
  "lib/system/notifications/mutations": typeof lib_system_notifications_mutations;
  "lib/system/notifications/permissions": typeof lib_system_notifications_permissions;
  "lib/system/notifications/queries": typeof lib_system_notifications_queries;
  "lib/system/notifications/types": typeof lib_system_notifications_types;
  "lib/system/notifications/utils": typeof lib_system_notifications_utils;
  "lib/system/permission_requests/constants": typeof lib_system_permission_requests_constants;
  "lib/system/permission_requests/index": typeof lib_system_permission_requests_index;
  "lib/system/permission_requests/mutations": typeof lib_system_permission_requests_mutations;
  "lib/system/permission_requests/permissions": typeof lib_system_permission_requests_permissions;
  "lib/system/permission_requests/queries": typeof lib_system_permission_requests_queries;
  "lib/system/permission_requests/types": typeof lib_system_permission_requests_types;
  "lib/system/permission_requests/utils": typeof lib_system_permission_requests_utils;
  "lib/system/supporting/comments": typeof lib_system_supporting_comments;
  "lib/system/supporting/counters": typeof lib_system_supporting_counters;
  "lib/system/supporting/documents": typeof lib_system_supporting_documents;
  "lib/system/supporting/exchangeRates": typeof lib_system_supporting_exchangeRates;
  "lib/system/supporting/followupReminders": typeof lib_system_supporting_followupReminders;
  "lib/system/supporting/index": typeof lib_system_supporting_index;
  "lib/system/supporting/inquirySources": typeof lib_system_supporting_inquirySources;
  "lib/system/supporting/notifications": typeof lib_system_supporting_notifications;
  "lib/system/supporting/schemas": typeof lib_system_supporting_schemas;
  "lib/system/supporting/types": typeof lib_system_supporting_types;
  "lib/system/supporting/validators": typeof lib_system_supporting_validators;
  "lib/system/supporting/wikiEntries": typeof lib_system_supporting_wikiEntries;
  "lib/system/system_metrics/constants": typeof lib_system_system_metrics_constants;
  "lib/system/system_metrics/index": typeof lib_system_system_metrics_index;
  "lib/system/system_metrics/mutations": typeof lib_system_system_metrics_mutations;
  "lib/system/system_metrics/permissions": typeof lib_system_system_metrics_permissions;
  "lib/system/system_metrics/queries": typeof lib_system_system_metrics_queries;
  "lib/system/system_metrics/types": typeof lib_system_system_metrics_types;
  "lib/system/system_metrics/utils": typeof lib_system_system_metrics_utils;
  "lib/system/user_profiles/constants": typeof lib_system_user_profiles_constants;
  "lib/system/user_profiles/index": typeof lib_system_user_profiles_index;
  "lib/system/user_profiles/mutations": typeof lib_system_user_profiles_mutations;
  "lib/system/user_profiles/permissions": typeof lib_system_user_profiles_permissions;
  "lib/system/user_profiles/queries": typeof lib_system_user_profiles_queries;
  "lib/system/user_profiles/types": typeof lib_system_user_profiles_types;
  "lib/system/user_profiles/utils": typeof lib_system_user_profiles_utils;
  "lib/system/user_settings/user_model_preferences/constants": typeof lib_system_user_settings_user_model_preferences_constants;
  "lib/system/user_settings/user_model_preferences/index": typeof lib_system_user_settings_user_model_preferences_index;
  "lib/system/user_settings/user_model_preferences/mutations": typeof lib_system_user_settings_user_model_preferences_mutations;
  "lib/system/user_settings/user_model_preferences/permissions": typeof lib_system_user_settings_user_model_preferences_permissions;
  "lib/system/user_settings/user_model_preferences/queries": typeof lib_system_user_settings_user_model_preferences_queries;
  "lib/system/user_settings/user_model_preferences/types": typeof lib_system_user_settings_user_model_preferences_types;
  "lib/system/user_settings/user_model_preferences/utils": typeof lib_system_user_settings_user_model_preferences_utils;
  "lib/system/user_settings/user_settings/constants": typeof lib_system_user_settings_user_settings_constants;
  "lib/system/user_settings/user_settings/index": typeof lib_system_user_settings_user_settings_index;
  "lib/system/user_settings/user_settings/mutations": typeof lib_system_user_settings_user_settings_mutations;
  "lib/system/user_settings/user_settings/permissions": typeof lib_system_user_settings_user_settings_permissions;
  "lib/system/user_settings/user_settings/queries": typeof lib_system_user_settings_user_settings_queries;
  "lib/system/user_settings/user_settings/types": typeof lib_system_user_settings_user_settings_types;
  "lib/system/user_settings/user_settings/utils": typeof lib_system_user_settings_user_settings_utils;
  "lib/yourobc/accounting/constants": typeof lib_yourobc_accounting_constants;
  "lib/yourobc/accounting/index": typeof lib_yourobc_accounting_index;
  "lib/yourobc/accounting/mutations": typeof lib_yourobc_accounting_mutations;
  "lib/yourobc/accounting/permissions": typeof lib_yourobc_accounting_permissions;
  "lib/yourobc/accounting/queries": typeof lib_yourobc_accounting_queries;
  "lib/yourobc/accounting/types": typeof lib_yourobc_accounting_types;
  "lib/yourobc/accounting/utils": typeof lib_yourobc_accounting_utils;
  "lib/yourobc/couriers/constants": typeof lib_yourobc_couriers_constants;
  "lib/yourobc/couriers/index": typeof lib_yourobc_couriers_index;
  "lib/yourobc/couriers/mutations": typeof lib_yourobc_couriers_mutations;
  "lib/yourobc/couriers/permissions": typeof lib_yourobc_couriers_permissions;
  "lib/yourobc/couriers/queries": typeof lib_yourobc_couriers_queries;
  "lib/yourobc/couriers/types": typeof lib_yourobc_couriers_types;
  "lib/yourobc/couriers/utils": typeof lib_yourobc_couriers_utils;
  "lib/yourobc/customerMargins/constants": typeof lib_yourobc_customerMargins_constants;
  "lib/yourobc/customerMargins/index": typeof lib_yourobc_customerMargins_index;
  "lib/yourobc/customerMargins/mutations": typeof lib_yourobc_customerMargins_mutations;
  "lib/yourobc/customerMargins/permissions": typeof lib_yourobc_customerMargins_permissions;
  "lib/yourobc/customerMargins/queries": typeof lib_yourobc_customerMargins_queries;
  "lib/yourobc/customerMargins/types": typeof lib_yourobc_customerMargins_types;
  "lib/yourobc/customerMargins/utils": typeof lib_yourobc_customerMargins_utils;
  "lib/yourobc/customers/bulkHelpers": typeof lib_yourobc_customers_bulkHelpers;
  "lib/yourobc/customers/constants": typeof lib_yourobc_customers_constants;
  "lib/yourobc/customers/index": typeof lib_yourobc_customers_index;
  "lib/yourobc/customers/mutations": typeof lib_yourobc_customers_mutations;
  "lib/yourobc/customers/permissions": typeof lib_yourobc_customers_permissions;
  "lib/yourobc/customers/queries": typeof lib_yourobc_customers_queries;
  "lib/yourobc/customers/types": typeof lib_yourobc_customers_types;
  "lib/yourobc/customers/utils": typeof lib_yourobc_customers_utils;
  "lib/yourobc/dashboard/constants": typeof lib_yourobc_dashboard_constants;
  "lib/yourobc/dashboard/index": typeof lib_yourobc_dashboard_index;
  "lib/yourobc/dashboard/mutations": typeof lib_yourobc_dashboard_mutations;
  "lib/yourobc/dashboard/permissions": typeof lib_yourobc_dashboard_permissions;
  "lib/yourobc/dashboard/queries": typeof lib_yourobc_dashboard_queries;
  "lib/yourobc/dashboard/types": typeof lib_yourobc_dashboard_types;
  "lib/yourobc/dashboard/utils": typeof lib_yourobc_dashboard_utils;
  "lib/yourobc/employeeCommissions/constants": typeof lib_yourobc_employeeCommissions_constants;
  "lib/yourobc/employeeCommissions/index": typeof lib_yourobc_employeeCommissions_index;
  "lib/yourobc/employeeCommissions/mutations": typeof lib_yourobc_employeeCommissions_mutations;
  "lib/yourobc/employeeCommissions/permissions": typeof lib_yourobc_employeeCommissions_permissions;
  "lib/yourobc/employeeCommissions/queries": typeof lib_yourobc_employeeCommissions_queries;
  "lib/yourobc/employeeCommissions/types": typeof lib_yourobc_employeeCommissions_types;
  "lib/yourobc/employeeCommissions/utils": typeof lib_yourobc_employeeCommissions_utils;
  "lib/yourobc/employeeKPIs/constants": typeof lib_yourobc_employeeKPIs_constants;
  "lib/yourobc/employeeKPIs/index": typeof lib_yourobc_employeeKPIs_index;
  "lib/yourobc/employeeKPIs/mutations": typeof lib_yourobc_employeeKPIs_mutations;
  "lib/yourobc/employeeKPIs/permissions": typeof lib_yourobc_employeeKPIs_permissions;
  "lib/yourobc/employeeKPIs/queries": typeof lib_yourobc_employeeKPIs_queries;
  "lib/yourobc/employeeKPIs/types": typeof lib_yourobc_employeeKPIs_types;
  "lib/yourobc/employeeKPIs/utils": typeof lib_yourobc_employeeKPIs_utils;
  "lib/yourobc/employeeSessions/constants": typeof lib_yourobc_employeeSessions_constants;
  "lib/yourobc/employeeSessions/index": typeof lib_yourobc_employeeSessions_index;
  "lib/yourobc/employeeSessions/mutations": typeof lib_yourobc_employeeSessions_mutations;
  "lib/yourobc/employeeSessions/permissions": typeof lib_yourobc_employeeSessions_permissions;
  "lib/yourobc/employeeSessions/queries": typeof lib_yourobc_employeeSessions_queries;
  "lib/yourobc/employeeSessions/types": typeof lib_yourobc_employeeSessions_types;
  "lib/yourobc/employeeSessions/utils": typeof lib_yourobc_employeeSessions_utils;
  "lib/yourobc/employees/constants": typeof lib_yourobc_employees_constants;
  "lib/yourobc/employees/index": typeof lib_yourobc_employees_index;
  "lib/yourobc/employees/mutations": typeof lib_yourobc_employees_mutations;
  "lib/yourobc/employees/permissions": typeof lib_yourobc_employees_permissions;
  "lib/yourobc/employees/queries": typeof lib_yourobc_employees_queries;
  "lib/yourobc/employees/types": typeof lib_yourobc_employees_types;
  "lib/yourobc/employees/utils": typeof lib_yourobc_employees_utils;
  "lib/yourobc/invoices/constants": typeof lib_yourobc_invoices_constants;
  "lib/yourobc/invoices/index": typeof lib_yourobc_invoices_index;
  "lib/yourobc/invoices/mutations": typeof lib_yourobc_invoices_mutations;
  "lib/yourobc/invoices/permissions": typeof lib_yourobc_invoices_permissions;
  "lib/yourobc/invoices/queries": typeof lib_yourobc_invoices_queries;
  "lib/yourobc/invoices/types": typeof lib_yourobc_invoices_types;
  "lib/yourobc/invoices/utils": typeof lib_yourobc_invoices_utils;
  "lib/yourobc/partners/constants": typeof lib_yourobc_partners_constants;
  "lib/yourobc/partners/index": typeof lib_yourobc_partners_index;
  "lib/yourobc/partners/mutations": typeof lib_yourobc_partners_mutations;
  "lib/yourobc/partners/permissions": typeof lib_yourobc_partners_permissions;
  "lib/yourobc/partners/queries": typeof lib_yourobc_partners_queries;
  "lib/yourobc/partners/types": typeof lib_yourobc_partners_types;
  "lib/yourobc/partners/utils": typeof lib_yourobc_partners_utils;
  "lib/yourobc/quotes/constants": typeof lib_yourobc_quotes_constants;
  "lib/yourobc/quotes/index": typeof lib_yourobc_quotes_index;
  "lib/yourobc/quotes/mutations": typeof lib_yourobc_quotes_mutations;
  "lib/yourobc/quotes/permissions": typeof lib_yourobc_quotes_permissions;
  "lib/yourobc/quotes/queries": typeof lib_yourobc_quotes_queries;
  "lib/yourobc/quotes/types": typeof lib_yourobc_quotes_types;
  "lib/yourobc/quotes/utils": typeof lib_yourobc_quotes_utils;
  "lib/yourobc/shared/calculations": typeof lib_yourobc_shared_calculations;
  "lib/yourobc/shared/constants": typeof lib_yourobc_shared_constants;
  "lib/yourobc/shared/formatting": typeof lib_yourobc_shared_formatting;
  "lib/yourobc/shared/generators": typeof lib_yourobc_shared_generators;
  "lib/yourobc/shared/index": typeof lib_yourobc_shared_index;
  "lib/yourobc/shared/types": typeof lib_yourobc_shared_types;
  "lib/yourobc/shared/utils": typeof lib_yourobc_shared_utils;
  "lib/yourobc/shared/validation": typeof lib_yourobc_shared_validation;
  "lib/yourobc/shipments/constants": typeof lib_yourobc_shipments_constants;
  "lib/yourobc/shipments/index": typeof lib_yourobc_shipments_index;
  "lib/yourobc/shipments/mutations": typeof lib_yourobc_shipments_mutations;
  "lib/yourobc/shipments/permissions": typeof lib_yourobc_shipments_permissions;
  "lib/yourobc/shipments/queries": typeof lib_yourobc_shipments_queries;
  "lib/yourobc/shipments/types": typeof lib_yourobc_shipments_types;
  "lib/yourobc/shipments/utils": typeof lib_yourobc_shipments_utils;
  "lib/yourobc/statistics/constants": typeof lib_yourobc_statistics_constants;
  "lib/yourobc/statistics/index": typeof lib_yourobc_statistics_index;
  "lib/yourobc/statistics/mutations": typeof lib_yourobc_statistics_mutations;
  "lib/yourobc/statistics/permissions": typeof lib_yourobc_statistics_permissions;
  "lib/yourobc/statistics/queries": typeof lib_yourobc_statistics_queries;
  "lib/yourobc/statistics/types": typeof lib_yourobc_statistics_types;
  "lib/yourobc/statistics/utils": typeof lib_yourobc_statistics_utils;
  "lib/yourobc/supporting/constants": typeof lib_yourobc_supporting_constants;
  "lib/yourobc/supporting/index": typeof lib_yourobc_supporting_index;
  "lib/yourobc/supporting/mutations": typeof lib_yourobc_supporting_mutations;
  "lib/yourobc/supporting/permissions": typeof lib_yourobc_supporting_permissions;
  "lib/yourobc/supporting/queries": typeof lib_yourobc_supporting_queries;
  "lib/yourobc/supporting/types": typeof lib_yourobc_supporting_types;
  "lib/yourobc/supporting/utils": typeof lib_yourobc_supporting_utils;
  "lib/yourobc/tasks/constants": typeof lib_yourobc_tasks_constants;
  "lib/yourobc/tasks/index": typeof lib_yourobc_tasks_index;
  "lib/yourobc/tasks/mutations": typeof lib_yourobc_tasks_mutations;
  "lib/yourobc/tasks/permissions": typeof lib_yourobc_tasks_permissions;
  "lib/yourobc/tasks/queries": typeof lib_yourobc_tasks_queries;
  "lib/yourobc/tasks/types": typeof lib_yourobc_tasks_types;
  "lib/yourobc/tasks/utils": typeof lib_yourobc_tasks_utils;
  "lib/yourobc/trackingMessages/constants": typeof lib_yourobc_trackingMessages_constants;
  "lib/yourobc/trackingMessages/index": typeof lib_yourobc_trackingMessages_index;
  "lib/yourobc/trackingMessages/mutations": typeof lib_yourobc_trackingMessages_mutations;
  "lib/yourobc/trackingMessages/permissions": typeof lib_yourobc_trackingMessages_permissions;
  "lib/yourobc/trackingMessages/queries": typeof lib_yourobc_trackingMessages_queries;
  "lib/yourobc/trackingMessages/types": typeof lib_yourobc_trackingMessages_types;
  "lib/yourobc/trackingMessages/utils": typeof lib_yourobc_trackingMessages_utils;
  "schema/base": typeof schema_base;
  "schema/system/analytics/analytics": typeof schema_system_analytics_analytics;
  "schema/system/analytics/schemas": typeof schema_system_analytics_schemas;
  "schema/system/analytics/types": typeof schema_system_analytics_types;
  "schema/system/analytics/validators": typeof schema_system_analytics_validators;
  "schema/system/appConfigs/appConfigs": typeof schema_system_appConfigs_appConfigs;
  "schema/system/appConfigs/schemas": typeof schema_system_appConfigs_schemas;
  "schema/system/appConfigs/types": typeof schema_system_appConfigs_types;
  "schema/system/appConfigs/validators": typeof schema_system_appConfigs_validators;
  "schema/system/appSettings/appSettings": typeof schema_system_appSettings_appSettings;
  "schema/system/appSettings/schemas": typeof schema_system_appSettings_schemas;
  "schema/system/appSettings/validators": typeof schema_system_appSettings_validators;
  "schema/system/appThemeSettings/appThemeSettings": typeof schema_system_appThemeSettings_appThemeSettings;
  "schema/system/appThemeSettings/schemas": typeof schema_system_appThemeSettings_schemas;
  "schema/system/appThemeSettings/validators": typeof schema_system_appThemeSettings_validators;
  "schema/system/auditLogs/auditLogs": typeof schema_system_auditLogs_auditLogs;
  "schema/system/auditLogs/schemas": typeof schema_system_auditLogs_schemas;
  "schema/system/auditLogs/types": typeof schema_system_auditLogs_types;
  "schema/system/auditLogs/validators": typeof schema_system_auditLogs_validators;
  "schema/system/dashboards/dashboards": typeof schema_system_dashboards_dashboards;
  "schema/system/dashboards/schemas": typeof schema_system_dashboards_schemas;
  "schema/system/dashboards/types": typeof schema_system_dashboards_types;
  "schema/system/dashboards/validators": typeof schema_system_dashboards_validators;
  "schema/system/email/configs": typeof schema_system_email_configs;
  "schema/system/email/logs": typeof schema_system_email_logs;
  "schema/system/email/schemas": typeof schema_system_email_schemas;
  "schema/system/email/templates": typeof schema_system_email_templates;
  "schema/system/email/types": typeof schema_system_email_types;
  "schema/system/email/validators": typeof schema_system_email_validators;
  "schema/system/index": typeof schema_system_index;
  "schema/system/notifications/notifications": typeof schema_system_notifications_notifications;
  "schema/system/notifications/schemas": typeof schema_system_notifications_schemas;
  "schema/system/notifications/types": typeof schema_system_notifications_types;
  "schema/system/notifications/validators": typeof schema_system_notifications_validators;
  "schema/system/permissionRequests/permissionRequests": typeof schema_system_permissionRequests_permissionRequests;
  "schema/system/permissionRequests/schemas": typeof schema_system_permissionRequests_schemas;
  "schema/system/permissionRequests/types": typeof schema_system_permissionRequests_types;
  "schema/system/permissionRequests/validators": typeof schema_system_permissionRequests_validators;
  "schema/system/schemas": typeof schema_system_schemas;
  "schema/system/supporting/comments": typeof schema_system_supporting_comments;
  "schema/system/supporting/counters": typeof schema_system_supporting_counters;
  "schema/system/supporting/documents": typeof schema_system_supporting_documents;
  "schema/system/supporting/exchangeRates": typeof schema_system_supporting_exchangeRates;
  "schema/system/supporting/followupReminders": typeof schema_system_supporting_followupReminders;
  "schema/system/supporting/index": typeof schema_system_supporting_index;
  "schema/system/supporting/inquirySources": typeof schema_system_supporting_inquirySources;
  "schema/system/supporting/notifications": typeof schema_system_supporting_notifications;
  "schema/system/supporting/schemas": typeof schema_system_supporting_schemas;
  "schema/system/supporting/types": typeof schema_system_supporting_types;
  "schema/system/supporting/validators": typeof schema_system_supporting_validators;
  "schema/system/supporting/wikiEntries": typeof schema_system_supporting_wikiEntries;
  "schema/system/systemMetrics/schemas": typeof schema_system_systemMetrics_schemas;
  "schema/system/systemMetrics/systemMetrics": typeof schema_system_systemMetrics_systemMetrics;
  "schema/system/systemMetrics/validators": typeof schema_system_systemMetrics_validators;
  "schema/system/types": typeof schema_system_types;
  "schema/system/user_profiles/schemas": typeof schema_system_user_profiles_schemas;
  "schema/system/user_profiles/types": typeof schema_system_user_profiles_types;
  "schema/system/user_profiles/user_profiles": typeof schema_system_user_profiles_user_profiles;
  "schema/system/user_profiles/validators": typeof schema_system_user_profiles_validators;
  "schema/system/user_settings/user_model_preferences/schemas": typeof schema_system_user_settings_user_model_preferences_schemas;
  "schema/system/user_settings/user_model_preferences/types": typeof schema_system_user_settings_user_model_preferences_types;
  "schema/system/user_settings/user_model_preferences/user_model_preferences": typeof schema_system_user_settings_user_model_preferences_user_model_preferences;
  "schema/system/user_settings/user_model_preferences/validators": typeof schema_system_user_settings_user_model_preferences_validators;
  "schema/system/user_settings/user_settings/schemas": typeof schema_system_user_settings_user_settings_schemas;
  "schema/system/user_settings/user_settings/types": typeof schema_system_user_settings_user_settings_types;
  "schema/system/user_settings/user_settings/user_settings": typeof schema_system_user_settings_user_settings_user_settings;
  "schema/system/user_settings/user_settings/validators": typeof schema_system_user_settings_user_settings_validators;
  "schema/system/validators": typeof schema_system_validators;
  "schema/yourobc/accounting/accounting": typeof schema_yourobc_accounting_accounting;
  "schema/yourobc/accounting/accountingDashboardCache": typeof schema_yourobc_accounting_accountingDashboardCache;
  "schema/yourobc/accounting/incomingInvoiceTracking": typeof schema_yourobc_accounting_incomingInvoiceTracking;
  "schema/yourobc/accounting/index": typeof schema_yourobc_accounting_index;
  "schema/yourobc/accounting/invoiceAutoGenLog": typeof schema_yourobc_accounting_invoiceAutoGenLog;
  "schema/yourobc/accounting/invoiceNumbering": typeof schema_yourobc_accounting_invoiceNumbering;
  "schema/yourobc/accounting/schemas": typeof schema_yourobc_accounting_schemas;
  "schema/yourobc/accounting/statementOfAccounts": typeof schema_yourobc_accounting_statementOfAccounts;
  "schema/yourobc/accounting/types": typeof schema_yourobc_accounting_types;
  "schema/yourobc/accounting/validators": typeof schema_yourobc_accounting_validators;
  "schema/yourobc/couriers/commissions": typeof schema_yourobc_couriers_commissions;
  "schema/yourobc/couriers/couriers": typeof schema_yourobc_couriers_couriers;
  "schema/yourobc/couriers/index": typeof schema_yourobc_couriers_index;
  "schema/yourobc/couriers/schemas": typeof schema_yourobc_couriers_schemas;
  "schema/yourobc/couriers/types": typeof schema_yourobc_couriers_types;
  "schema/yourobc/couriers/validators": typeof schema_yourobc_couriers_validators;
  "schema/yourobc/customerMargins/contactLog": typeof schema_yourobc_customerMargins_contactLog;
  "schema/yourobc/customerMargins/customerAnalytics": typeof schema_yourobc_customerMargins_customerAnalytics;
  "schema/yourobc/customerMargins/customerDunningConfig": typeof schema_yourobc_customerMargins_customerDunningConfig;
  "schema/yourobc/customerMargins/customerMargins": typeof schema_yourobc_customerMargins_customerMargins;
  "schema/yourobc/customerMargins/index": typeof schema_yourobc_customerMargins_index;
  "schema/yourobc/customerMargins/schemas": typeof schema_yourobc_customerMargins_schemas;
  "schema/yourobc/customerMargins/types": typeof schema_yourobc_customerMargins_types;
  "schema/yourobc/customerMargins/validators": typeof schema_yourobc_customerMargins_validators;
  "schema/yourobc/customers/customers": typeof schema_yourobc_customers_customers;
  "schema/yourobc/customers/index": typeof schema_yourobc_customers_index;
  "schema/yourobc/customers/schemas": typeof schema_yourobc_customers_schemas;
  "schema/yourobc/customers/types": typeof schema_yourobc_customers_types;
  "schema/yourobc/customers/validators": typeof schema_yourobc_customers_validators;
  "schema/yourobc/dashboard/dashboardAlertAcknowledgments": typeof schema_yourobc_dashboard_dashboardAlertAcknowledgments;
  "schema/yourobc/dashboard/index": typeof schema_yourobc_dashboard_index;
  "schema/yourobc/dashboard/schemas": typeof schema_yourobc_dashboard_schemas;
  "schema/yourobc/dashboard/types": typeof schema_yourobc_dashboard_types;
  "schema/yourobc/dashboard/validators": typeof schema_yourobc_dashboard_validators;
  "schema/yourobc/employeeCommissions/employeeCommissionRules": typeof schema_yourobc_employeeCommissions_employeeCommissionRules;
  "schema/yourobc/employeeCommissions/employeeCommissions": typeof schema_yourobc_employeeCommissions_employeeCommissions;
  "schema/yourobc/employeeCommissions/index": typeof schema_yourobc_employeeCommissions_index;
  "schema/yourobc/employeeCommissions/schemas": typeof schema_yourobc_employeeCommissions_schemas;
  "schema/yourobc/employeeCommissions/types": typeof schema_yourobc_employeeCommissions_types;
  "schema/yourobc/employeeCommissions/validators": typeof schema_yourobc_employeeCommissions_validators;
  "schema/yourobc/employeeKPIs/employeeKPIs": typeof schema_yourobc_employeeKPIs_employeeKPIs;
  "schema/yourobc/employeeKPIs/employeeTargets": typeof schema_yourobc_employeeKPIs_employeeTargets;
  "schema/yourobc/employeeKPIs/index": typeof schema_yourobc_employeeKPIs_index;
  "schema/yourobc/employeeKPIs/schemas": typeof schema_yourobc_employeeKPIs_schemas;
  "schema/yourobc/employeeKPIs/types": typeof schema_yourobc_employeeKPIs_types;
  "schema/yourobc/employeeKPIs/validators": typeof schema_yourobc_employeeKPIs_validators;
  "schema/yourobc/employeeSessions/employeeSessions": typeof schema_yourobc_employeeSessions_employeeSessions;
  "schema/yourobc/employeeSessions/index": typeof schema_yourobc_employeeSessions_index;
  "schema/yourobc/employeeSessions/schemas": typeof schema_yourobc_employeeSessions_schemas;
  "schema/yourobc/employeeSessions/types": typeof schema_yourobc_employeeSessions_types;
  "schema/yourobc/employeeSessions/validators": typeof schema_yourobc_employeeSessions_validators;
  "schema/yourobc/employeeSessions/workHoursSummary": typeof schema_yourobc_employeeSessions_workHoursSummary;
  "schema/yourobc/employees/employees": typeof schema_yourobc_employees_employees;
  "schema/yourobc/employees/index": typeof schema_yourobc_employees_index;
  "schema/yourobc/employees/schemas": typeof schema_yourobc_employees_schemas;
  "schema/yourobc/employees/types": typeof schema_yourobc_employees_types;
  "schema/yourobc/employees/vacationDays": typeof schema_yourobc_employees_vacationDays;
  "schema/yourobc/employees/validators": typeof schema_yourobc_employees_validators;
  "schema/yourobc/index": typeof schema_yourobc_index;
  "schema/yourobc/invoices/index": typeof schema_yourobc_invoices_index;
  "schema/yourobc/invoices/invoices": typeof schema_yourobc_invoices_invoices;
  "schema/yourobc/invoices/schemas": typeof schema_yourobc_invoices_schemas;
  "schema/yourobc/invoices/types": typeof schema_yourobc_invoices_types;
  "schema/yourobc/invoices/validators": typeof schema_yourobc_invoices_validators;
  "schema/yourobc/partners/index": typeof schema_yourobc_partners_index;
  "schema/yourobc/partners/partners": typeof schema_yourobc_partners_partners;
  "schema/yourobc/partners/schemas": typeof schema_yourobc_partners_schemas;
  "schema/yourobc/partners/types": typeof schema_yourobc_partners_types;
  "schema/yourobc/partners/validators": typeof schema_yourobc_partners_validators;
  "schema/yourobc/quotes/index": typeof schema_yourobc_quotes_index;
  "schema/yourobc/quotes/quotes": typeof schema_yourobc_quotes_quotes;
  "schema/yourobc/quotes/schemas": typeof schema_yourobc_quotes_schemas;
  "schema/yourobc/quotes/types": typeof schema_yourobc_quotes_types;
  "schema/yourobc/quotes/validators": typeof schema_yourobc_quotes_validators;
  "schema/yourobc/schemas": typeof schema_yourobc_schemas;
  "schema/yourobc/shipments/index": typeof schema_yourobc_shipments_index;
  "schema/yourobc/shipments/schemas": typeof schema_yourobc_shipments_schemas;
  "schema/yourobc/shipments/shipmentStatusHistory": typeof schema_yourobc_shipments_shipmentStatusHistory;
  "schema/yourobc/shipments/shipments": typeof schema_yourobc_shipments_shipments;
  "schema/yourobc/shipments/types": typeof schema_yourobc_shipments_types;
  "schema/yourobc/shipments/validators": typeof schema_yourobc_shipments_validators;
  "schema/yourobc/statistics/employeeCosts": typeof schema_yourobc_statistics_employeeCosts;
  "schema/yourobc/statistics/index": typeof schema_yourobc_statistics_index;
  "schema/yourobc/statistics/kpiCache": typeof schema_yourobc_statistics_kpiCache;
  "schema/yourobc/statistics/kpiTargets": typeof schema_yourobc_statistics_kpiTargets;
  "schema/yourobc/statistics/miscExpenses": typeof schema_yourobc_statistics_miscExpenses;
  "schema/yourobc/statistics/officeCosts": typeof schema_yourobc_statistics_officeCosts;
  "schema/yourobc/statistics/schemas": typeof schema_yourobc_statistics_schemas;
  "schema/yourobc/statistics/types": typeof schema_yourobc_statistics_types;
  "schema/yourobc/statistics/validators": typeof schema_yourobc_statistics_validators;
  "schema/yourobc/supporting/comments": typeof schema_yourobc_supporting_comments;
  "schema/yourobc/supporting/counters": typeof schema_yourobc_supporting_counters;
  "schema/yourobc/supporting/documents": typeof schema_yourobc_supporting_documents;
  "schema/yourobc/supporting/exchangeRates": typeof schema_yourobc_supporting_exchangeRates;
  "schema/yourobc/supporting/followupReminders": typeof schema_yourobc_supporting_followupReminders;
  "schema/yourobc/supporting/index": typeof schema_yourobc_supporting_index;
  "schema/yourobc/supporting/inquirySources": typeof schema_yourobc_supporting_inquirySources;
  "schema/yourobc/supporting/notifications": typeof schema_yourobc_supporting_notifications;
  "schema/yourobc/supporting/schemas": typeof schema_yourobc_supporting_schemas;
  "schema/yourobc/supporting/types": typeof schema_yourobc_supporting_types;
  "schema/yourobc/supporting/validators": typeof schema_yourobc_supporting_validators;
  "schema/yourobc/supporting/wikiEntries": typeof schema_yourobc_supporting_wikiEntries;
  "schema/yourobc/tasks/index": typeof schema_yourobc_tasks_index;
  "schema/yourobc/tasks/schemas": typeof schema_yourobc_tasks_schemas;
  "schema/yourobc/tasks/tasks": typeof schema_yourobc_tasks_tasks;
  "schema/yourobc/tasks/types": typeof schema_yourobc_tasks_types;
  "schema/yourobc/tasks/validators": typeof schema_yourobc_tasks_validators;
  "schema/yourobc/trackingMessages/index": typeof schema_yourobc_trackingMessages_index;
  "schema/yourobc/trackingMessages/schemas": typeof schema_yourobc_trackingMessages_schemas;
  "schema/yourobc/trackingMessages/trackingMessages": typeof schema_yourobc_trackingMessages_trackingMessages;
  "schema/yourobc/trackingMessages/types": typeof schema_yourobc_trackingMessages_types;
  "schema/yourobc/trackingMessages/validators": typeof schema_yourobc_trackingMessages_validators;
  "schema/yourobc/types": typeof schema_yourobc_types;
  "schema/yourobc/validators": typeof schema_yourobc_validators;
  "shared/config/publicId": typeof shared_config_publicId;
  "shared/errors": typeof shared_errors;
  "shared/security/encryption": typeof shared_security_encryption;
  "shared/security/envHelper": typeof shared_security_envHelper;
  "shared/security/keyCache": typeof shared_security_keyCache;
  "shared/security/rate_limiter": typeof shared_security_rate_limiter;
  "shared/utils/id_resolution": typeof shared_utils_id_resolution;
  "shared/utils/publicId": typeof shared_utils_publicId;
  "shared/validators": typeof shared_validators;
  "test/authTest": typeof test_authTest;
  types: typeof types;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
