// convex/lib/system/user_settings/user_model_preferences/mutations.ts
// Write operations for user_model_preferences module

import { mutation } from '@/generated/server';
import { v } from 'convex/values';
import { requireCurrentUser } from '@/shared/auth.helper';
import { generateUniquePublicId } from '@/shared/utils/publicId';
import { userModelPreferencesValidators } from '@/schema/system/user_settings/user_model_preferences/validators';
import { validateModelPreferences, trimModelPreferencesData, generateModelPreferencesDisplayName, getDefaultModelPreferences } from './utils';
import { requireEditModelPreferencesAccess, requireDeleteModelPreferencesAccess } from './permissions';
import type { UserModelPreferencesId } from './types';

/**
 * Update user model preferences - GUIDE compliant 7-step mutation
 */
export const updateUserModelPreferences = mutation({
  args: {
    data: v.object({
      defaultLanguageModel: v.optional(v.string()),
      defaultEmbeddingModel: v.optional(v.string()),
      defaultImageModel: v.optional(v.string()),
      defaultMultimodalModel: v.optional(v.string()),
      favoriteModels: v.optional(v.array(v.string())),
      hiddenProviders: v.optional(v.array(v.string())),
      preferredView: v.optional(userModelPreferencesValidators.preferredView),
      sortPreference: v.optional(userModelPreferencesValidators.sortPreference),
      testingDefaults: v.optional(userModelPreferencesValidators.testingDefaults),
    }),
  },
  handler: async (ctx, { data }): Promise<UserModelPreferencesId> => {
    const user = await requireCurrentUser(ctx);
    const existing = await ctx.db.query('userModelPreferences').withIndex('by_user_id', (q) => q.eq('userId', user._id)).filter((q) => q.eq(q.field('deletedAt'), undefined)).unique();
    if (existing) { await requireEditModelPreferencesAccess(ctx, existing, user); }
    const trimmedData = trimModelPreferencesData(data);
    const errors = validateModelPreferences(trimmedData);
    if (errors.length > 0) { throw new Error('Validation failed: ' + errors.join(', ')); }
    const now = Date.now();
    if (existing) {
      const updateData: any = { updatedAt: now, updatedBy: user._id, version: existing.version + 1 };
      if (trimmedData.defaultLanguageModel !== undefined) updateData.defaultLanguageModel = trimmedData.defaultLanguageModel;
      if (trimmedData.defaultEmbeddingModel !== undefined) updateData.defaultEmbeddingModel = trimmedData.defaultEmbeddingModel;
      if (trimmedData.defaultImageModel !== undefined) updateData.defaultImageModel = trimmedData.defaultImageModel;
      if (trimmedData.defaultMultimodalModel !== undefined) updateData.defaultMultimodalModel = trimmedData.defaultMultimodalModel;
      if (trimmedData.favoriteModels !== undefined) updateData.favoriteModels = trimmedData.favoriteModels;
      if (trimmedData.hiddenProviders !== undefined) updateData.hiddenProviders = trimmedData.hiddenProviders;
      if (trimmedData.preferredView !== undefined) updateData.preferredView = trimmedData.preferredView;
      if (trimmedData.sortPreference !== undefined) updateData.sortPreference = trimmedData.sortPreference;
      if (trimmedData.testingDefaults !== undefined) updateData.testingDefaults = trimmedData.testingDefaults;
      await ctx.db.patch(existing._id, updateData);
      await ctx.db.insert('auditLogs', { userId: user._id, userName: user.name || user.email || 'Unknown User', action: 'user_model_preferences.updated', entityType: 'system_user_model_preferences', entityId: existing.publicId, entityTitle: existing.displayName, description: 'Updated model preferences: ' + existing.displayName, metadata: { changes: trimmedData }, createdAt: now, createdBy: user._id, updatedAt: now });
      return existing._id;
    } else {
      const defaults = getDefaultModelPreferences();
      const publicId = await generateUniquePublicId(ctx, 'userModelPreferences');
      const displayName = generateModelPreferencesDisplayName(user.name || user.email || 'User');
      const preferencesId = await ctx.db.insert('userModelPreferences', { publicId, displayName, ownerId: user._id, userId: user._id, defaultLanguageModel: trimmedData.defaultLanguageModel || defaults.defaultLanguageModel, defaultEmbeddingModel: trimmedData.defaultEmbeddingModel || defaults.defaultEmbeddingModel, defaultImageModel: trimmedData.defaultImageModel || defaults.defaultImageModel, defaultMultimodalModel: trimmedData.defaultMultimodalModel || defaults.defaultMultimodalModel, favoriteModels: trimmedData.favoriteModels || defaults.favoriteModels, hiddenProviders: trimmedData.hiddenProviders || defaults.hiddenProviders, preferredView: trimmedData.preferredView || defaults.preferredView, sortPreference: trimmedData.sortPreference || defaults.sortPreference, testingDefaults: trimmedData.testingDefaults || defaults.testingDefaults, version: 1, metadata: undefined, createdAt: now, createdBy: user._id, updatedAt: now, updatedBy: user._id });
      await ctx.db.insert('auditLogs', { userId: user._id, userName: user.name || user.email || 'Unknown User', action: 'user_model_preferences.created', entityType: 'system_user_model_preferences', entityId: publicId, entityTitle: displayName, description: 'Created model preferences: ' + displayName, metadata: { data: trimmedData }, createdAt: now, createdBy: user._id, updatedAt: now });
      return preferencesId;
    }
  },
});

export const setDefaultModel = mutation({ args: { modelId: v.string(), modelType: v.string() }, handler: async (ctx, { modelId, modelType }): Promise<UserModelPreferencesId> => { const user = await requireCurrentUser(ctx); const existing = await ctx.db.query('userModelPreferences').withIndex('by_user_id', (q) => q.eq('userId', user._id)).filter((q) => q.eq(q.field('deletedAt'), undefined)).unique(); if (existing) { await requireEditModelPreferencesAccess(ctx, existing, user); } const now = Date.now(); const updateData: any = { updatedAt: now, updatedBy: user._id }; if (modelType === 'language') updateData.defaultLanguageModel = modelId.trim(); else if (modelType === 'embedding') updateData.defaultEmbeddingModel = modelId.trim(); else if (modelType === 'image') updateData.defaultImageModel = modelId.trim(); else if (modelType === 'multimodal') updateData.defaultMultimodalModel = modelId.trim(); else throw new Error('Invalid model type'); if (existing) { await ctx.db.patch(existing._id, { ...updateData, version: existing.version + 1 }); await ctx.db.insert('auditLogs', { userId: user._id, userName: user.name || user.email || 'Unknown User', action: 'user_model_preferences.default_set', entityType: 'system_user_model_preferences', entityId: existing.publicId, entityTitle: existing.displayName, description: 'Set default ' + modelType + ': ' + existing.displayName, metadata: { modelId, modelType }, createdAt: now, createdBy: user._id, updatedAt: now }); return existing._id; } else { const defaults = getDefaultModelPreferences(); const publicId = await generateUniquePublicId(ctx, 'userModelPreferences'); const displayName = generateModelPreferencesDisplayName(user.name || user.email || 'User'); const preferencesId = await ctx.db.insert('userModelPreferences', { publicId, displayName, ownerId: user._id, userId: user._id, ...defaults, ...updateData, version: 1, createdAt: now, createdBy: user._id }); await ctx.db.insert('auditLogs', { userId: user._id, userName: user.name || user.email || 'Unknown User', action: 'user_model_preferences.created', entityType: 'system_user_model_preferences', entityId: publicId, entityTitle: displayName, description: 'Created and set default: ' + displayName, metadata: { modelId, modelType }, createdAt: now, createdBy: user._id, updatedAt: now }); return preferencesId; } } });

export const toggleFavoriteModel = mutation({ args: { modelId: v.string() }, handler: async (ctx, { modelId }): Promise<UserModelPreferencesId> => { const user = await requireCurrentUser(ctx); const existing = await ctx.db.query('userModelPreferences').withIndex('by_user_id', (q) => q.eq('userId', user._id)).filter((q) => q.eq(q.field('deletedAt'), undefined)).unique(); if (existing) { await requireEditModelPreferencesAccess(ctx, existing, user); } const trimmedModelId = modelId.trim(); const currentFavorites = existing?.favoriteModels || []; const isFavorite = currentFavorites.includes(trimmedModelId); const newFavorites = isFavorite ? currentFavorites.filter(id => id !== trimmedModelId) : [...currentFavorites, trimmedModelId]; const errors = validateModelPreferences({ favoriteModels: newFavorites }); if (errors.length > 0) { throw new Error('Validation failed: ' + errors.join(', ')); } const now = Date.now(); if (existing) { await ctx.db.patch(existing._id, { favoriteModels: newFavorites, version: existing.version + 1, updatedAt: now, updatedBy: user._id }); await ctx.db.insert('auditLogs', { userId: user._id, userName: user.name || user.email || 'Unknown User', action: isFavorite ? 'user_model_preferences.unfavorited' : 'user_model_preferences.favorited', entityType: 'system_user_model_preferences', entityId: existing.publicId, entityTitle: existing.displayName, description: (isFavorite ? 'Removed from' : 'Added to') + ' favorites: ' + existing.displayName, metadata: { modelId: trimmedModelId }, createdAt: now, createdBy: user._id, updatedAt: now }); return existing._id; } else { const defaults = getDefaultModelPreferences(); const publicId = await generateUniquePublicId(ctx, 'userModelPreferences'); const displayName = generateModelPreferencesDisplayName(user.name || user.email || 'User'); const preferencesId = await ctx.db.insert('userModelPreferences', { publicId, displayName, ownerId: user._id, userId: user._id, ...defaults, favoriteModels: newFavorites, version: 1, createdAt: now, createdBy: user._id, updatedAt: now, updatedBy: user._id }); await ctx.db.insert('auditLogs', { userId: user._id, userName: user.name || user.email || 'Unknown User', action: 'user_model_preferences.created', entityType: 'system_user_model_preferences', entityId: publicId, entityTitle: displayName, description: 'Created and favorited: ' + displayName, metadata: { modelId: trimmedModelId }, createdAt: now, createdBy: user._id, updatedAt: now }); return preferencesId; } } });

export const clearDefaultModel = mutation({ args: { modelType: v.union(v.literal('language'), v.literal('embedding'), v.literal('image'), v.literal('multimodal')) }, handler: async (ctx, { modelType }): Promise<UserModelPreferencesId | null> => { const user = await requireCurrentUser(ctx); const existing = await ctx.db.query('userModelPreferences').withIndex('by_user_id', (q) => q.eq('userId', user._id)).filter((q) => q.eq(q.field('deletedAt'), undefined)).unique(); if (!existing) return null; await requireEditModelPreferencesAccess(ctx, existing, user); const now = Date.now(); const updateData: any = { updatedAt: now, updatedBy: user._id, version: existing.version + 1 }; if (modelType === 'language') updateData.defaultLanguageModel = undefined; else if (modelType === 'embedding') updateData.defaultEmbeddingModel = undefined; else if (modelType === 'image') updateData.defaultImageModel = undefined; else updateData.defaultMultimodalModel = undefined; await ctx.db.patch(existing._id, updateData); await ctx.db.insert('auditLogs', { userId: user._id, userName: user.name || user.email || 'Unknown User', action: 'user_model_preferences.default_cleared', entityType: 'system_user_model_preferences', entityId: existing.publicId, entityTitle: existing.displayName, description: 'Cleared default ' + modelType + ': ' + existing.displayName, metadata: { modelType }, createdAt: now, createdBy: user._id, updatedAt: now }); return existing._id; } });

export const resetUserModelPreferences = mutation({ args: {}, handler: async (ctx): Promise<UserModelPreferencesId> => { const user = await requireCurrentUser(ctx); const existing = await ctx.db.query('userModelPreferences').withIndex('by_user_id', (q) => q.eq('userId', user._id)).filter((q) => q.eq(q.field('deletedAt'), undefined)).unique(); if (existing) { await requireEditModelPreferencesAccess(ctx, existing, user); } const defaults = getDefaultModelPreferences(); const now = Date.now(); if (existing) { await ctx.db.patch(existing._id, { ...defaults, publicId: existing.publicId, displayName: existing.displayName, ownerId: existing.ownerId, userId: existing.userId, version: existing.version + 1, updatedAt: now, updatedBy: user._id }); await ctx.db.insert('auditLogs', { userId: user._id, userName: user.name || user.email || 'Unknown User', action: 'user_model_preferences.reset', entityType: 'system_user_model_preferences', entityId: existing.publicId, entityTitle: existing.displayName, description: 'Reset: ' + existing.displayName, createdAt: now, createdBy: user._id, updatedAt: now }); return existing._id; } else { const publicId = await generateUniquePublicId(ctx, 'userModelPreferences'); const displayName = generateModelPreferencesDisplayName(user.name || user.email || 'User'); const preferencesId = await ctx.db.insert('userModelPreferences', { publicId, displayName, ownerId: user._id, userId: user._id, ...defaults, version: 1, createdAt: now, createdBy: user._id, updatedAt: now, updatedBy: user._id }); await ctx.db.insert('auditLogs', { userId: user._id, userName: user.name || user.email || 'Unknown User', action: 'user_model_preferences.created', entityType: 'system_user_model_preferences', entityId: publicId, entityTitle: displayName, description: 'Created default: ' + displayName, createdAt: now, createdBy: user._id, updatedAt: now }); return preferencesId; } } });

export const deleteUserModelPreferences = mutation({ args: {}, handler: async (ctx): Promise<UserModelPreferencesId> => { const user = await requireCurrentUser(ctx); const preferences = await ctx.db.query('userModelPreferences').withIndex('by_user_id', (q) => q.eq('userId', user._id)).filter((q) => q.eq(q.field('deletedAt'), undefined)).unique(); if (!preferences) { throw new Error('Preferences not found'); } await requireDeleteModelPreferencesAccess(preferences, user); const now = Date.now(); await ctx.db.patch(preferences._id, { deletedAt: now, deletedBy: user._id, updatedAt: now, updatedBy: user._id }); await ctx.db.insert('auditLogs', { userId: user._id, userName: user.name || user.email || 'Unknown User', action: 'user_model_preferences.deleted', entityType: 'system_user_model_preferences', entityId: preferences.publicId, entityTitle: preferences.displayName, description: 'Deleted: ' + preferences.displayName, createdAt: now, createdBy: user._id, updatedAt: now }); return preferences._id; } });
